### PR TITLE
[feat] Svg export

### PR DESCRIPTION
**Pull request by Jolanrensen**
As discussed https://github.com/data2viz/data2viz/issues/239, this adds ```Viz.toSVG()``` support.

Support is almost finished, almost everything works. What still needs to be done:

- Gradients need more tests (especially radial)
- More tests in general
- Text is a bit misaligned (too far downwards)
- Chart<*>.toSVG()

If there are any suggestions for tests or text alignment, let me know!

### CODE REVIEW

**Comment by Jolanrensen** [comment]
Could I also ask how you build the whole project with JavaFX? Most tutorials I find talk about using a JavaFX plugin in the gradle.build files, but I obviously don't want to modify those.

**Comment by Jolanrensen** [comment]
> JavaFX is included in Java 8. So there is nothing special to do apart from using Java 8. Then, it's efficient to run the tests. CleanShot2021-10-14-17 44 31

got it, thanks! turns out I was using OpenJDK 11, it works fine with Oracle's JDK8 :)

**Comment by Jolanrensen** [comment]
Gradients and text is fixed, so all we now need is maybe to combine the tests back, add some more tests and then we're good!
Also conversion from a Chart to SVG would be nice, but the Viz created in newViz, VizContainer is hidden. Currently the only way to convert a chart to SVG is to make a VizContainer myself and save the Viz object that is created in newViz.

**Comment by gzoritchak** [comment]
I think we can give access to the underlying list of viz of a VizContainer and create a VizContainerExtension function to generate an SVG from a VizContainer.

**Comment by Jolanrensen** [comment]
For future information. I found that most programs cannot convert the SVGs to something else, except for rsvg. It can successfully convert the SVGs to PDF.

**Pull request merged**
